### ISSUE TITLE
Deleting journals on the left causes page height decrease and then cutting off the widget

### ISSUE THREAD

**Issue by BernicoJC** [cse110-sp24-group18/cse110-sp24-group18#136]
Way to recreate the bug:
- Delete several journals in the journal list

**Comment by michaelcheungkm** [comment]
Fixed in [03c1541](https://github.com/cse110-sp24-group18/cse110-sp24-group18/commit/03c154128edb7104cfd432f0cf58d8e481ed398b)[03c1541](https://github.com/cse110-sp24-group18/cse110-sp24-group18/commit/03c154128edb7104cfd432f0cf58d8e481ed398b)
