### ISSUE TITLE
Clicking on the date moves the summary button to the right

### ISSUE THREAD

**Issue by BernicoJC** [cse110-sp24-group18/cse110-sp24-group18#138]
When clicking the date button of the journal, the summary button will be slightly moved to the right while the date menu is open and will return afterward.

Way to recreate the bug:
- Pick a journal
- Select the date button (as if ready for typing)

Possible solutions:
- Lock the summary button to the right
- Fix the CSS of the date button so they don't increase in size to right.

**Comment by michaelcheungkm** [comment]
[03c1541](https://github.com/cse110-sp24-group18/cse110-sp24-group18/commit/03c154128edb7104cfd432f0cf58d8e481ed398b)
