### ISSUE TITLE
Titles and features in the header not alligned

### ISSUE THREAD

**Issue by BernicoJC** [cse110-sp24-group18/cse110-sp24-group18#139]
All 3 of the things on the headers don't align visually.

Way to recreate bug: visual

Possible solutions: CSS fix

**Comment by michaelcheungkm** [comment]
Fixed in [03c1541](https://github.com/cse110-sp24-group18/cse110-sp24-group18/commit/03c154128edb7104cfd432f0cf58d8e481ed398b)
