### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by BernicoJC** [cse110-sp24-group18/cse110-sp24-group18#95]
Assigned to: Rick

**Comment by rickrodness** [comment]
### Update: Added Basic Transitions

**Description:**
- Implemented basic CSS transitions to enhance user interactions.
- Applied transitions to buttons, links, and note field for added visual feedback.

**Code Example:**
```css
.button {
    transition: opacity 0.3s ease-in-out, transform 0.3s ease-in-out;
}
.button:hover {
    opacity: 0.7;
    transform: scale(1.05);
}

**Comment by rickrodness** [comment]
Next Steps: 
- Push changes to main for testing.
- After verification, finalize and push to documentation.

**Comment by rickrodness** [comment]
https://github.com/cse110-sp24-group18/cse110-sp24-group18/assets/146511854/f8f496b9-be4d-4bf4-8706-392f7f8e390f

**Comment by BernicoJC** [comment]
Animation implemented to the backend branch, effectively having it integrated.
